- id: clang-format
  name: formatter of C/C++ code
  description: Run clang-format against C/C++ header and source files
  language: system
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: clang-format -i
  args: ["-style=Google"]
- id: cpplint
  name: linter for Google C++ Style Guide
  description: Run cpplint against C/C++ header and source files
  language: python
  files: \.(h\+\+|h|hh|hxx|hpp|cuh|c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: cpplint
- id: cppcheck
  name: static analyzer of C/C++ code
  description: Run cppcheck against C/C++ source files
  language: system
  files: \.(c|cc|cpp|cu|c\+\+|cxx|tpp|txx)$
  entry: cppcheck --error-exitcode=1
